import { Box, Flex, Heading } from '@chakra-ui/react'
import React from 'react'
import Head from 'next/head'
import Nav from '../Nav/Nav'

const Header = (props = {}) => {
    return (<Flex
        justifyContent={'space-between'}
        backgroundColor={{
            base: "primary.900",
            lg: "background.900",
        }}
        w={'100%'}
        px={{ base: 4, lg: 0 }}
        py={4}>
            <Head>
        <title>Blog title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Box>
            <Heading
                as={'h1'}
            >Title</Heading>
        </Box>
        <Box>
            <Nav />
        </Box>
    </Flex>)
}

export default Header